### PR TITLE
Additional Features for Curved Staircase Compound Brushes

### PR DESCRIPTION
**Pull request by Henry00IS**
* Added "Fill To Bottom" identical to the linear staircases.
* Added "Build Torus" to easily build walls around curved staircases.
* Fixed the normals for "Counter Clockwise" mode.
* Updated the inspector to use more of a SabreCSG theme.
* Moved some identical copy and pasted code into separate functions.

newcurvedstairfeatures

### CODE REVIEW

**Comment by Henry00IS** [comment]
Added beautiful sloped floors and ceilings that can both be combined for amazing things.
image
image

### This pull request can be reviewed and merged now.

**Comment by sabresaurus** [comment]
I'd suggest renaming "Build Torus" to something else. A torus is a donut shape, this is technically a hollow cylinder. I'd probably also suggest splitting out that function into a separate compound brush, from a user's perspective it doesn't really make sense to create a stair brush which you then turn into an arch/curved wall.

**Comment by sabresaurus** [comment]
Other than that this looks great

**Comment by Henry00IS** [comment]
The reason the torus (what's a better name for it? maybe "walls") was added is to make walls around curved staircases. The default cylinder doesn't align properly. This [Zelda Ocarina of Time](https://youtu.be/PM5Omd-LqvE?t=297) level is where I got the inspiration to include that feature. How else are you ever going to make such a corridor?

**Comment by Henry00IS** [comment]
This is its intended use:

image

**Pull request merged**
