### PR TITLE
Material Update Number 2

### PR DESCRIPTION
**Pull request by Kerfuffles**
## Additions:
* Two new metal materials
* Two new glass materials
* One wood material
* One grass material
* One sand material

## Changes:
* Changed Example Materials folder structure. There is now individual folders for each texture type (glass, metal, etc.) next to the materials, under Textures.

## Images:
image
image

### CODE REVIEW

**Comment by Constaneer** [comment]
Awesome!

**Comment by Kerfuffles** [comment]
I completely re-designed the treadplate material, as it had horrible tiling issues and didnt mip very well. This one should be a lot better.

image

**Comment by Kerfuffles** [comment]
Updated the metal treadplate material (looks more metallic now), and fixed incorrect specular on the plain glass material.

image

**Comment by Henry00IS** [comment]
Very impressive! Some of the best materials I have seen in a long time!

**Pull request merged**
