### PR TITLE
Green collision material and wireframe for collision-only brushes.

### PR DESCRIPTION
**Pull request by Henry00IS**
It got so confusing to differentiate between additive brushes and collision brushes that I decided to give them a unique color:

Appearance of several brushes

### CODE REVIEW

**Comment by Constaneer** [comment]
That’s actually a fantastic idea! This might go good with a sort of trigger system, where you can make the model a trigger (with out having to go through the collision mesh)

**Comment by sabresaurus** [comment]
Nice! Might be worth trying a different colour, this is pretty close to the Exclude visual

image

**Comment by Constaneer** [comment]
Maybe green would be good

**Comment by Henry00IS** [comment]
I agree, green is used by Unity for collision as well.

**Comment by Henry00IS** [comment]
Here you go:

Brushes

**Comment by Henry00IS** [comment]
I have added a collision icon for the brushes in the hierarchy.

Collision brushes and icon

**Pull request merged**
