### PR TITLE
Reflection Probes Usage build settings

### PR DESCRIPTION
**Pull request by Kerfuffles**
In reference to issue #82.

+ Added "Common Fixes" section to CSGModelInspector.
+ Added a toggle + enum to change ReflectionProbeUsage for the entire CSGModel to build settings.

image

When the option is disabled, it uses the default setting "Blend Probes".

### CODE REVIEW

**Comment by Henry00IS** [comment]
Nice work! I made a small change however. At the moment every rebuild will reset the "MaterialMesh" renderer settings and any customization isn't retained. So the checkbox doesn't actually allow you to keep your existing settings and doesn't offer any functionality over just having the enum set to Blend Probes (that would be identical to the current behavior of SabreCSG). As such I moved the Reflection Probes enum underneath Shadow Casting Mode and the default is simply Blend Probes.

image

Are you happy for me to merge it?

**Comment by Kerfuffles** [comment]
Works for me! The purpose I had for the toggle was to just use the default setting that MeshRenderer sets when enabled. It gets set to BlendProbes by default when the mesh is built anyways. I just happened to have it set to off in the image, but it did default to BlendProbes in the inspector.

Though, question. Does the reset apply to after a run or just after build? I didn't notice any reset post-build in my testing.

**Comment by Henry00IS** [comment]
And no running the game doesn't affect it. If you never ever rebuild the CSG model again you can change the individual mesh renderer settings as well.

**Comment by Kerfuffles** [comment]
I was pressing force rebuild. Huh, Interesting. Thanks for the correction though!

**Comment by Henry00IS** [comment]
@Kerfuffles This is totally the wrong place to do this, but I would love to invite you to [join the Discord group](https://discord.gg/pFAS5rK)!

**Pull request merged**
