### PR TITLE
Project cleanup and documentation

### PR DESCRIPTION
**Pull request by Henry00IS**
The first of many files that has been cleaned up and documented. Let's see how this goes.

**The Plan**
- Removing commented code and TODO statements that have already been fixed.
- ~~Keeping to the Unity standard of having camelCase properties.~~
- Providing in-depth and useful C# summary documentation.
- Replacing, adding and completing bits of code that just make more sense.
- Keep the existing functionality identical. We clean logic, not change it.
- Make more things public for the Runtime CSG API.
- Hopefully not break anything in the process.

**The Goal**
- Having a clean and documented source will allow people to use the Runtime CSG more effectively.
- It may attract more contributors that can implement their ideas with ease.
- Improve code maintainability with less spaghetti.
And personally to learn enough in the process to contribute even more.

If this project never gets finished, the parts that were done are nice regardless.

### CODE REVIEW

**Comment by sabresaurus** [comment]
"Keeping to the Unity standard of having camelCase properties."

SabreCSG has been built to the [Microsoft C# standards](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions) which means that properties (and anything public) should be PascalCase. While it's important that Unity's code itself maintains their consistent naming, most C# follows the official language standards (which makes it more consistent with other libraries. CSG code also has many applications outside of Unity and it's possible that other projects will want to use parts of SabreCSG code).

**Comment by Henry00IS** [comment]
Trust me I dislike that silly camelCase in Unity as well. It's a nightmare. Well good that I started this pull request otherwise we'd have a problem later on. :)

**Comment by Henry00IS** [comment]
I have some questions about Edge.cs. Since I am also documenting and proofreading all of the math I came across some oddities.

First of all to check whether lines are parallel:

**public bool Collinear(Edge other)**
`bool parallel = dot > 1 - EPSILON;`

**public bool Intersects(Edge other)**
`bool parallel = Mathf.Abs(dot) > 1 - EPSILON`

Why did you remove `Mathf.Abs`? I made a `public bool Parallel(Edge other)` method and all of the CSG results and adjacency tests appear to be identical when using the `Mathf.Abs` version. You have a comment of the `Mathf.Abs` version in `Collinear` and deliberately changed it.

---

**public bool Collinear(Edge other)**
This first checks whether two edges are parallel. Then compares whether either vertex position matches either vertex position of the other edge. Sure this means they are collinear but by definition there could be a gap between both edges, or they could partially intersect and they are still collinear like in this great interactive example: [https://www.mathopenref.com/collinear.html](https://www.mathopenref.com/collinear.html)

The return value of this function is wrong in all of these cases? Would correcting this equation break something in the polygon factory? It's the only reference to this method.

**Comment by sabresaurus** [comment]
It looks like Collinear isn't actually being used, the code that references
it in PolygonFactory it was an early experiment into optimising polygons by
collapsing shared edges. It didn't work particularly well as you still had
T-junctions, the more recent optimisation code works considerably better
(although of course still can't fix the geometry completely).

I would suggest removing the Collinear method and the
OptimizeCoplanarPolygons (and dependent methods/fields) from PolygonFactory.

The other thing to check with these refactors is that it doesn't introduce
performance regressions, some of the code may look odd (for example there
are some linked lists in BrushBuilder, but lists elsewhere) but has been
rewritten that way to speed up performance. I can send you a couple of
benchmark scenes I use.

Barnaby Smith
Director | Sabresaurus Ltd. <http://sabresaurus.com>

<http://sabresaurus.com/>
Follow Sabresaurus on Twitter <https://twitter.com/sabresaurus>

**Comment by Henry00IS** [comment]
Thanks for the feedback Barnaby, you were totally right.

I found an alternative for the `myEdge.Collinear(otherEdge)` method in `EdgeUtility.EdgeMatches` (vague name) and decided to forward calls to that method as it may come in handy to someone.

As for the performance, I think I actually improved it by skipping some if checks in `bool Intersects(Edge other)` once you know it's not even parallel. I will keep your advice in mind and be very careful. And sure those scenes would sure come in handy. :)

**Comment by Henry00IS** [comment]
Question about Polygon, the `ExcludeFromFinal` or "isTemporary", what effect does it have? As it's not serialized it's clearly only used during the build process. Could you please elaborate, when should the programmer use this?

**Comment by sabresaurus** [comment]
ExcludeFromFinal/isTemporary is used to mark polygons that are only created during the build process. For example if you subtract cube B from cube A, SabreCSG will split cube A into chunks by cube B. In order to maintain convex solid chunks additional polygons are created on those split planes so that we can still determine if a point is inside/outside the chunk.

**Comment by Henry00IS** [comment]
Resolved merge conflicts and updated to SabreCSG 1.6.1. Without affecting the PR's "Files changed"!

**Comment by Henry00IS** [comment]
This PR has been manually merged into individual PRs and proof-read to make sure there were no errors.

**Pull request closed without merging**
