### PR TITLE
2DSE: Cross-Platform Rendering and Mac Retina display fixes.

### PR DESCRIPTION
**Pull request by Henry00IS**
It should be [like this video](https://cdn.discordapp.com/attachments/448072131620634633/449655318574792714/2DSE.mp4).

Windows and Linux now render properly. Mac should be a lot better but I require feedback from someone with a Retina display. Does it work like in the video?

### CODE REVIEW

**Comment by sabresaurus** [comment]
image

**Comment by Henry00IS** [comment]
I wish someone could provide me with some video footage so I could actually see how the alignment behaves now and have them test a couple trial & error iterations with me. The fixes in this PR should at least guarantee nothing is up-side down like loaded background images. Every time I ask around they are like "sure I will help" and stop replying. I wonder if I really have to purchase a MacBook Pro just to fix this PR...

**Comment by sabresaurus** [comment]
I'm working on this issue

**Comment by sabresaurus** [comment]
@Henry00IS 
This is not a perfect fix, I've spent quite a few hours trying to fix this issue properly and I've not come across an easy consistent way to do this across Metal,DirectX/OpenGL and Retina/Non-Retina. It's hard to tell if the root cause is a Unity bug or a misunderstanding on our part, but given how inconsistent the behaviour is I wouldn't be surprised if this is a Unity bug.

I've updated this pull request with improvements that now make it reasonably consistent across those platforms, there are still some minor off by one pixel issues in certain configurations but it's significantly better than what's in master currently. 

I have tested this in Unity 2017.3.1 on:
* MacBook Pro - Retina - Metal
* MacBook Pro - Retina - OpenGL
* MacBook Pro - Low Res (Non-Retina) - Metal
* MacBook Pro - Low Res (Non-Retina) - OpenGL
* Windows - DirectX
* Windows - OpenGL

As mentioned above it functions acceptably on all these platforms. If this pull request looks okay to you I'd suggest merging it to stabilise master, then creating a new issue to represent multi-platform improvements to the 2DSE grid rendering.

**Comment by Henry00IS** [comment]
@sabresaurus 
I can't possibly find the right words to thank you enough. I am currently on a vacation to my mom and this good news made it even better! Truly, thank you so much! 🙇

It's so nice to see you back in action! The rendering is fine under Windows and I trust your judgement for the other platforms. If the bottom half of the grid is off by one pixel that even happens on Windows sometimes, depends on the window size and scroll position, lines tend to get twice as thick, nothing too serious, because I switch from positive modulo into negative modulo calculations, there's a small hack that shifts things by one pixel. But again that's only the bottom half of the grid.

**Pull request merged**
