### PR TITLE
Toolbar rework

### LINKED ISSUE #205: UI Improvement: group Add/Subtract/Volume/NoCSG
These 4 types are all mutually exclusive, yet cover a dropdown and two separate buttons in the UI. These could be moved to the brush inspector itself, and be more clearly exclusive options; such as using radio buttons or a dropdown selection. This should remove any possible confusion about using any two of the types together on one brush (which is impossible anyway)

### PR DESCRIPTION
**Pull request by jmickle66666666**
screenshot 2019-01-08 18 58 08

Addresses #205 #206 

* Moved all non-essential viewport and grid settings to a togglable menu, to clean up the clutter of the toolbar. This allows more space and clearer labels for the moved options.
* Move the brush count from the toolbar to the CSGModel inspector, since it is not a number that needs to always be immediately referenced.
* Moved all brush-specific settings and operations to a contextual menu that appears only when brushes are selected. This includes the "Flip X/Y/Z" and "Snap Center" buttons from the Resize Toolbar. As a part of this, BrushUtility.Flip had to be changed to accept Brush instead of PrimitiveBrush
* Move most of the primitive brushes to a togglable menu, clearing up a lot of space from mostly infrequently used buttons. The cube was kept as it is still a useful button to have on hand at any time. Added a new icon for the "More" option in the primitives menu
* Reduced the height of the toolbar from two lines to one, since so much space was saved. However, added functionality to split into two lines again in case the scene viewport is too small to show everything
* Removed the "Prefs" and "Disable" buttons from the toolbar, since they seem to be mostly redundant, and take up unnecessary space.

### CODE REVIEW

**Comment by sabresaurus** [comment]
Firstly great work, personally I think this is a vast improvement.

Some feedback:

screenshot 2019-01-08 19 44 57

- Seems like some of the text is light grey on my Editor (2017.3.1f1), see above image
- It might make sense to hide Brush Settings when not in Resize of Vertex tools (e.g. it's not useful in the face tool for example and probably gives the wrong context in the other tools too)
- The >>> button seems to have gone, it's used for the pop-out version of the top UI
- The checkboxes are considerably harder to press than the old toggles

Some other thoughts that are less pressing:

- The Flip X,Y,Z buttons might be nicer as GUILayout.Toolbar()
- The grid settings say "Rotation snapping" and "Snap angle", it might be better to rename it to "Angle snapping" just so it's clear to new users the two settings are the same.
- Tooltips that show the shortcuts would be nice, e.g. hovering over Grid snapping it could tell you that press / would toggle it.

**Comment by jmickle66666666** [comment]
Ok, fixed up those issues. Thanks for the feedback!

The >>> button I can't account for. I don't remember it myself and definitely didn't touch any code that involved it. I assume it was removed in a previous commit somewhere?

While the checkboxes are more difficult to press than the old toggles, the old toggles are a non-standard UI element to fit the toolbar, whereas the new windows I created were styled after the inspector and followed the layout that does. It's fair to assume any SabreCSG user is already used to using checkboxes in the inspector.

**Comment by jmickle66666666** [comment]
brushmenu2

Just discovered an issue with the brush menu; it disappears when you are resizing a brush.

**Comment by vertxxyz** [comment]
All the more visibility 😃

**Comment by jmickle66666666** [comment]
brushmenu3

Fixed!

**Comment by Constaneer** [comment]
The grid size doesn't change the box size when the digit is higher then 3

**Comment by Constaneer** [comment]
The viewport settings gui hides when in Face mode

**Comment by Henry00IS** [comment]
Brilliant work! Thanks for fixing the toolbar selection too. This new interface will surely help many people! 😁

**Pull request merged**
